
obj-y := main.o

##################################
# Kbuild application targets
##################################


export SPINE_DIR := $(realpath ../../dependency)


export APP := $(notdir $(shell pwd))


-include $(SPINE_DIR)/scripts/Makefile.wrapper

            